# Generated by Django 4.2.8 on 2023-12-30 19:53

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('greeting', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to=home.models.profile_files)),
                ('home_image', models.ImageField(upload_to=home.models.profile_files)),
                ('birthday', models.DateField(null=True)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('block1_detail', models.CharField(max_length=50)),
                ('block1_number', models.IntegerField()),
                ('block2_detail', models.CharField(max_length=50)),
                ('block2_number', models.IntegerField()),
                ('block3_detail', models.CharField(max_length=50)),
                ('block3_number', models.IntegerField()),
                ('block4_detail', models.CharField(max_length=50)),
                ('block4_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('main_image', models.ImageField(upload_to=home.models.service_files)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('main_image', models.ImageField(upload_to=home.models.profile_files)),
                ('optional_image1', models.ImageField(blank=True, null=True, upload_to=home.models.profile_files)),
                ('optional_image2', models.ImageField(blank=True, null=True, upload_to=home.models.profile_files)),
                ('optional_image3', models.ImageField(blank=True, null=True, upload_to=home.models.profile_files)),
                ('link', models.URLField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.services')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
