# Generated by Django 4.2.8 on 2023-12-30 23:52

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.ImageField(upload_to=home.models.project_files),
        ),
        migrations.AlterField(
            model_name='project',
            name='optional_image1',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.project_files),
        ),
        migrations.AlterField(
            model_name='project',
            name='optional_image2',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.project_files),
        ),
        migrations.AlterField(
            model_name='project',
            name='optional_image3',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.project_files),
        ),
    ]
