# Generated by Django 4.2.8 on 2023-12-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_project_client_project_date_alter_project_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='insta',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
